fields:
  block_content:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    info:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    body:
      type: text_summary_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_format: 0
        compare_summary: 0
    field_background_media:
      type: entity_reference_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_entity_reference: 1
    field_banner_cta:
      type: link_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_title: 0
        compare_uri: 1
    field_banner_title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_block_link:
      type: link_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_title: 0
        compare_uri: 1
    field_quick_action:
      type: link_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_title: 0
        compare_uri: 1
    field_quick_action_icon:
      type: hidden
      settings: {  }
  crop:
    langcode:
      type: hidden
      settings: {  }
    entity_id:
      type: hidden
      settings: {  }
    entity_type:
      type: hidden
      settings: {  }
    uri:
      type: hidden
      settings: {  }
    height:
      type: hidden
      settings: {  }
    width:
      type: hidden
      settings: {  }
    x:
      type: hidden
      settings: {  }
    'y':
      type: hidden
      settings: {  }
    revision_timestamp:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
  media:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    revision_log_message:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    uid:
      type: hidden
      settings: {  }
    name:
      type: hidden
      settings: {  }
    thumbnail:
      type: image_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 0
        compare_alt_field: 1
        compare_title_field: 1
        property_separator: nl
        show_thumbnail: 1
    created:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    field_media_audio_file:
      type: file_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 1
        compare_description_field: 0
        compare_display_field: 0
        property_separator: nl
    field_media_document:
      type: file_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 1
        compare_description_field: 0
        compare_display_field: 0
        property_separator: nl
    field_media_image:
      type: image_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 0
        compare_alt_field: 1
        compare_title_field: 1
        property_separator: nl
        show_thumbnail: 1
    field_media_oembed_video:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_media_video_file:
      type: file_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 1
        compare_description_field: 0
        compare_display_field: 0
        property_separator: nl
  menu_link_content:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    revision_log_message:
      type: hidden
      settings: {  }
    enabled:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    description:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    link:
      type: hidden
      settings: {  }
    external:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
  node:
    langcode:
      type: hidden
      settings: {  }
    revision_timestamp:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    uid:
      type: entity_reference_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_entity_reference: 1
    title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    created:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    changed:
      type: hidden
      settings: {  }
    promote:
      type: hidden
      settings: {  }
    sticky:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    body:
      type: text_summary_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_format: 0
        compare_summary: 0
    comment_node_article:
      type: comment_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_key: 0
        compare_string: 1
    comment_node_page:
      type: comment_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_key: 0
        compare_string: 1
    field_background_image:
      type: entity_reference_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_entity_reference: 1
    field_basic_page_reaction:
      type: hidden
      settings: {  }
    field_data_classification:
      type: list_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare: key
    field_event_date:
      type: hidden
      settings: {  }
    field_event_location:
      type: address_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_event_online:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_event_online_text:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_hide_location:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_intro:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_map_location:
      type: geofield_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_news_article_reaction:
      type: hidden
      settings: {  }
    field_related_content:
      type: entity_reference_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_entity_reference: 1
    field_tags:
      type: entity_reference_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_entity_reference: 1
    field_webform_file_upload:
      type: file_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        show_id: 1
        compare_description_field: 0
        compare_display_field: 0
        property_separator: nl
    webform:
      type: hidden
      settings: {  }
  path_alias:
    langcode:
      type: hidden
      settings: {  }
    path:
      type: hidden
      settings: {  }
    alias:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
  taxonomy_term:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    revision_log_message:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    name:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    description:
      type: text_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
        compare_format: 0
    parent:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    field_address:
      type: address_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
  paragraph:
    langcode:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    created:
      type: hidden
      settings: {  }
    parent_id:
      type: hidden
      settings: {  }
    parent_type:
      type: hidden
      settings: {  }
    parent_field_name:
      type: hidden
      settings: {  }
    behavior_settings:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
